name: ci

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Determine image tag
        run: |
          TAG=${{  github.ref_name }}
          echo "TAG=$TAG" >> "$GITHUB_ENV"
      - name: Build image
        run: docker build -t marketron-app .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag marketron-app \
          registry.digitalocean.com/marketron-production/maprketron-app:${{ env.TAG }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/marketron-production/marketron-app:${{ env.TAG }}
